- launchdarkly-android-client/src/main/java/com/launchdarkly/android/LDClient.java
- launchdarkly-android-client/src/main/java/com/launchdarkly/android/UserManager.java
This PR ensures that both `UserManager.setCurrentUser` and `updateProcessor.Start` have completed before the `LDClient` instance is returned by `LDClient#init`, ensuring that the client is ready when the `Future<LDClient>` succeeds.
> LDClient.init should wait on both setCurrentUser and updateProcessor.start

- CHANGELOG.md
- launchdarkly-android-client/build.gradle
A customer reported a `ConcurrentModificationException` in `unregisterListener`. I could reproduce this issue by calling `unregisterListener` after registering the same listener twice. I fixed this issue by using an Iterator when removing the listener and also storing unique listeners.
> Fix the potential ConcurrentModificationException in unregisterListener

- CHANGELOG.md
- README.md
- launchdarkly-android-client/build.gradle
- launchdarkly-android-client/src/androidTest/java/com/launchdarkly/android/LDUserTest.java
- launchdarkly-android-client/src/main/java/com/launchdarkly/android/LDUser.java
- launchdarkly-android-client/src/main/java/com/launchdarkly/android/response/BaseUserSharedPreferences.java
* `ClassCastException` when calling `variation` methods due to internal storage schema changes between releases 2.3.x and 2.4.0
* `LDUser.Builder.custom()` no longer returns `UnsupportedOperationException`
> Version 2.5.1

- CHANGELOG.md
- README.md
- launchdarkly-android-client/build.gradle
- launchdarkly-android-client/src/main/java/com/launchdarkly/android/Throttler.java
* Restored support for initializing `LDClient` on non-main threads
> Version 2.5.3

- LICENSE.txt
This repo has referenced the Apache license since [2016](https://github.com/launchdarkly/android-client/commit/0e49c40712a0d21f4dca4509836a30859fb10a5b#diff-db8c608de96cfcc5c26c05958eb82627R72), but we didn't include the license body in-line. This PR rectifies that.
> Add Apache license body to repo

- README.md
For some time we've supported consumer Proguard rules which are included in the `aar` library distributions, and automatically bundled into Proguard configurations for client applications. The readme now reflects this, but includes a link to the up to date Proguard configuration if manual configuration is needed. It also includes mention of the more recent Android specific code shrinking tool R8. Thanks to #68 for the suggestion.
> Update readme to make it clear manual proguard configuration should be unnecessary 

- .circleci/config.yml
- CHANGELOG.md
- example/build.gradle
- launchdarkly-android-client-sdk/build.gradle
- launchdarkly-android-client-sdk/src/androidTest/java/com/launchdarkly/android/LDClientTest.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/android/DefaultEventProcessor.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/android/Foreground.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/android/LDClient.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/android/LDClientInterface.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/android/LDConfig.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/android/LDCountryCode.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/android/LDUser.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/android/PollingUpdater.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/android/SummaryEventSharedPreferences.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/android/response/FlagsResponse.java
- Removed possibility of fatal `SecurityException` on Samsung devices that would be triggered when the SDK attempted to register an alarm to trigger a future poll when the application process already had 500 alarms registered. This limit is only present on Samsung's versions of Android Lollipop and later. The SDK will now catch this error if it occurs to prevent killing the host application.
- Rarely, the client would deliver its initial "identify" event to LaunchDarkly immediately rather than waiting for the configured flush interval.
- Fixed some malformed Javadoc comments.
> Release 2.9.1

- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/LDUtil.java
N/A
When user devices(below Android 10) connect wifi and vpn, the isInternetConnected method will return false and 
caused LD to not work.
So I add nwc.hasTransport(NetworkCapabilities.TRANSPORT_VPN) to perfect this logical judgment.
N/A
**Additional context**
N/A
> Fix isInternetConnected return false when user connect wifi and vpn (below Android 10)

- launchdarkly-android-client-sdk/src/androidTest/java/com/launchdarkly/sdk/android/LDClientTest.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/LDClient.java
N/A
When `diagnosticOptOut` is `true` and the events buffer is full, a null pointer exception will be thrown when trying to send an event. Example stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.launchdarkly.sdk.android.DiagnosticStore.incrementDroppedEventCount()' on a null object reference
at com.launchdarkly.sdk.android.LDClient.sendEvent(LDClient.java:668)
at com.launchdarkly.sdk.android.LDClient.identifyInternal(LDClient.java:314)
at com.launchdarkly.sdk.android.LDClient.identifyInstances(LDClient.java:335)
at com.launchdarkly.sdk.android.LDClient.identify(LDClient.java:301)
at com.launchdarkly.sdk.android.LDClientTest.testEventBufferFillsUp(LDClientTest.java:661) …
```
> Fix NullPointerException when event buffer is full

- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/Throttler.java
See: #162 
Throttler::run and Throttler::attemptRun are the two functions that can syncrhonize both itself and
ConnectivityManager in that order, ConnectivityManager itself usually syncrhonizes on
itself then on Throttler by calling its functions. Because Throttler::run is run on a separate
thread this becomes a problem as the order of locking is different. Removing synchronize
from Throttler::run will restore the order as the runnable will lock ConnectivityManager.
Throttler::attemptRun is only called from ConnectivityManager and after it locks ConnectivityManager
so Throttler::attemptRun should not require any changes.
No alternatives considered
> Do not syncrhonize Throttler::run

- .ldrelease/publish.sh
Because we use the io.github.gradle-nexus.publish-plugin plugin, we need to use a different command.
> Fix .ldrelease/publish.sh

- launchdarkly-android-client-sdk/src/androidTest/java/com/launchdarkly/sdk/android/TimberLoggingTest.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/ConnectivityManager.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/DefaultEventProcessor.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/DefaultUserManager.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/DiagnosticEventProcessor.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/DiagnosticStore.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/Foreground.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/HttpFeatureFlagFetcher.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/LDClient.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/LDConfig.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/LDFutures.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/LDUtil.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/Migration.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/PollingUpdater.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/SharedPrefsFlagStore.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/SharedPrefsFlagStoreManager.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/SharedPrefsSummaryEventStore.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/StreamUpdateProcessor.java
#17 #38 #113 #147 #173  
All Timber events should have one common TAG - `LaunchDarklySdk`
Just fixing a bug.
**Additional context**
`Timber.tag(<..>)` had to be called before logging each event. Previous implementation called `tag()` once per app lifecycle.
> Set LaunchDarklySdk tag for all Timber events

- README.md
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/ContextDataManager.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/StreamingDataSource.java
- launchdarkly-android-client-sdk/src/test/java/com/launchdarkly/sdk/android/ContextDataManagerListenersTest.java
- launchdarkly-android-client-sdk/src/test/java/com/launchdarkly/sdk/android/StreamingDataSourceTest.java
- Streaming data connection to a relax proxy now calls the callback correctly after fetching the flag data.
- Flag listeners are now called correctly after `identify` results in flag value changes.
> prepare 4.2.3 release

- launchdarkly-android-client-sdk/consumer-proguard-rules.pro
refs #219
Update R8 config according to GSON docs https://github.com/google/gson/blob/main/Troubleshooting.md#-illegalstateexception-typetoken-must-be-created-with-a-type-argument--runtimeexception-missing-type-parameter
n/a
**Additional context**
n/a
> Update consumer-proguard-rules.pro for GSON

- .github/workflows/release-please.yml
This dry_run was hardcoded as a final protection against accidental publish during development.
> ci: removing hardcode dry_run

- .github/actions/publish/action.yml
- .github/workflows/publish.yml
Variables used in publish.sh were not in scope.  This change also makes the action a little more reusable.
> ci: fixing publish script variable visibility

- .github/actions/ci/action.yml
- launchdarkly-android-client-sdk/src/androidTest/java/com/launchdarkly/sdk/android/LDClientEventTest.java
236700
Eliminated recording of evaluation GET command which was leading to race condition in unit tests.
> ci: enabling ci tests after fixing test race condition

- launchdarkly-android-client-sdk/src/androidTest/java/com/launchdarkly/sdk/android/LDClientEndToEndTest.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/AndroidPlatformState.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/ClientContextImpl.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/ConnectivityManager.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/ContextDataManager.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/LDClient.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/StreamingDataSource.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/integrations/TestData.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/subsystems/ClientContext.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/subsystems/DataSourceUpdateSink.java
- launchdarkly-android-client-sdk/src/test/java/com/launchdarkly/sdk/android/ConnectivityManagerTest.java
- launchdarkly-android-client-sdk/src/test/java/com/launchdarkly/sdk/android/ContextDataManagerContextCachingTest.java
- launchdarkly-android-client-sdk/src/test/java/com/launchdarkly/sdk/android/ContextDataManagerFlagDataTest.java
- launchdarkly-android-client-sdk/src/test/java/com/launchdarkly/sdk/android/ContextDataManagerListenersTest.java
- shared-test-code/src/main/java/com/launchdarkly/sdk/android/MockComponents.java
SC-237349
Updated code so that ContextDataManager switches context independently of ConnectivityManager and ConnectivityManager is not in the path of context switching.
> fix: improved LDClient.identify(...) behavior when offline

- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/ConnectivityManager.java
- launchdarkly-android-client-sdk/src/test/java/com/launchdarkly/sdk/android/ConnectivityManagerTest.java
https://app.shortcut.com/launchdarkly/story/211876/android-sdk-connectioninformation-and-listeners-not-updated-correctly
The issue was introduced in version 4.X and is has affected 2 major versions.  The root of the issue is that from 3.x to 4.x, the code that sets the connection mode and kicks the last successful connection timestamp was moved out of the connectivity manager, so reconnects (which are handled inside the connectivity manager), were not handled.  The fix is to adjust the code so that cconnection information / connection timestamps are kicked when the reconnect logic succeeds or fails.
Refactoring to match iOS's logic of emitting an offline event when …
> fix: registered LDStatusListeners are now sent updates that result from a call to LDClient.identify(...)

- contract-tests/src/main/java/com/launchdarkly/sdktest/TestService.java
- launchdarkly-android-client-sdk/src/androidTest/java/com/launchdarkly/sdk/android/LDClientEventTest.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/DataModel.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/EnvironmentData.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/LDClient.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/integrations/TestData.java
- launchdarkly-android-client-sdk/src/test/java/com/launchdarkly/sdk/android/ConnectivityManagerTest.java
- launchdarkly-android-client-sdk/src/test/java/com/launchdarkly/sdk/android/EnvironmentDataTest.java
- launchdarkly-android-client-sdk/src/test/java/com/launchdarkly/sdk/android/FlagTest.java
- launchdarkly-android-client-sdk/src/test/java/com/launchdarkly/sdk/android/PersistentDataStoreWrapperTest.java
- shared-test-code/src/main/java/com/launchdarkly/sdk/android/DataSetBuilder.java
- shared-test-code/src/main/java/com/launchdarkly/sdk/android/FlagBuilder.java
> feat: Adds support for client-side prerequisite events

- .github/workflows/ci.yml
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/ComponentsImpl.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/LDClientInterface.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/PollingDataSource.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/integrations/PollingDataSourceBuilder.java
- launchdarkly-android-client-sdk/src/test/java/com/launchdarkly/sdk/android/PollingDataSourceTest.java
BEGIN_COMMIT_OVERRIDE
feat: polling data source now supports one shot configuration
fix: polling data source no longer reports initialized=true incorrectly when rate limiting delays first poll
END_COMMIT_OVERRIDE
Adds polling data source one shot mode.  Updated data source to support providing the max number of polls to make. 
Updated builder to calculate number of polls to make based on one shot configuration.
> feat: polling data source now supports one shot configuration

- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/EnvironmentData.java
After examining related code to a customer support case and #278, noticed this modification during iteration.  Theoretical issue is that modification during iteration, even if not resulting in ConcurrentModificationExceptions, could result in unpredictable iteration and could possibly skip sanitizing certain incoming flags.
Through bench testing and instrumentation testing, I was unable to reproduce the issue, but I suspect it may be dependent on the specific platform's implementation of the Map type that GSON will depend on.  Will deploy this fix and work with customers to confirm if the occurrences of the issue is eliminated.
> fix: correcting protocol parsing logic that may lead to incorrect sanitization of an incoming message from LD servers

- contract-tests/build.gradle
- contract-tests/src/main/java/com/launchdarkly/sdktest/HookCallbackService.java
- contract-tests/src/main/java/com/launchdarkly/sdktest/Representations.java
- contract-tests/src/main/java/com/launchdarkly/sdktest/SdkClientEntity.java
- contract-tests/src/main/java/com/launchdarkly/sdktest/TestHook.java
- contract-tests/src/main/java/com/launchdarkly/sdktest/TestService.java
- launchdarkly-android-client-sdk/src/androidTest/java/com/launchdarkly/sdk/android/LDClientHooksTest.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/Components.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/ComponentsImpl.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/HookRunner.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/LDClient.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/LDClientInterface.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/LDConfig.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/integrations/EvaluationSeriesContext.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/integrations/Hook.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/integrations/HookMetadata.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/integrations/HooksConfigurationBuilder.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/integrations/IdentifySeriesContext.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/integrations/IdentifySeriesResult.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/integrations/TrackSeriesContext.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/subsystems/HookConfiguration.java
- launchdarkly-android-client-sdk/src/test/java/com/launchdarkly/sdk/android/HookRunnerTest.java
- launchdarkly-android-client-sdk/src/test/java/com/launchdarkly/sdk/android/LDConfigTest.java
- launchdarkly-android-client-sdk/src/test/java/com/launchdarkly/sdk/android/integrations/HookConfigurationBuilderTest.java
- shared-test-code/src/main/java/com/launchdarkly/sdk/android/LogCaptureRule.java
> feat: Add hooks support

- launchdarkly-android-client-sdk/src/androidTest/java/com/launchdarkly/sdk/android/LDClientPluginsTest.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/Components.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/ComponentsImpl.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/LDClient.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/LDConfig.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/integrations/EnvironmentMetadata.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/integrations/Plugin.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/integrations/PluginMetadata.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/integrations/PluginsConfigurationBuilder.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/integrations/SdkMetadata.java
- launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/subsystems/PluginsConfiguration.java
- launchdarkly-android-client-sdk/src/test/java/com/launchdarkly/sdk/android/integrations/PluginConfigurationBuilderTest.java
SDK-1328
Adds plugins component, configuration builders, associated tests to implement plugins specification.
> chore: adds experimental plugin functionality
